version: "3.9"
services:
  app:
    container_name: simple-php
    image: php:8-fpm
    ports:
      - "9012:9012"
    volumes:
      - ./:/var/www/html
    command:
      - /bin/sh
      - -c
      - |
        docker-php-ext-install mysqli
        echo "security.limit_extensions =" >> /usr/local/etc/php-fpm.d/www.conf
        php-fpm
  web:
    container_name: simple-nginx
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - app
    restart: always