# Generated by Django 4.1.3 on 2022-11-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('repoURL', models.TextField()),
                ('branch', models.TextField()),
                ('status', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Thred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('psalmResult', models.TextField()),
                ('checkResult', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipe.tiket')),
            ],
        ),
    ]
