# Generated by Django 4.1.3 on 2022-11-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0002_thred_thred_num_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='jira_tiket',
            field=models.TextField(null=True),
        ),
    ]
