# Generated by Django 4.1.3 on 2022-11-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0003_tiket_jira_tiket'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='jira',
            field=models.TextField(null=True),
        ),
    ]
