# Generated by Django 4.1.3 on 2022-11-23 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0004_tiket_jira'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiket',
            old_name='jira',
            new_name='jira_id',
        ),
    ]
