# Generated by Django 4.1.3 on 2022-11-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0005_rename_jira_tiket_jira_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.TextField()),
                ('repoURL', models.TextField()),
                ('content', models.TextField()),
                ('tiket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipe.tiket')),
            ],
        ),
    ]
