# Generated by Django 4.1.3 on 2022-12-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipe', '0006_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiket',
            old_name='branch',
            new_name='pr_exec',
        ),
        migrations.RenameField(
            model_name='tiket',
            old_name='content',
            new_name='pr_num',
        ),
        migrations.RemoveField(
            model_name='tiket',
            name='repoURL',
        ),
        migrations.RemoveField(
            model_name='tiket',
            name='subject',
        ),
    ]
